// Regenerates src/abi.ts from the Foundry build output. Run `forge build` in contracts/ first.
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const artifact = resolve(here, '../../../contracts/out/CanteenOrders.sol/CanteenOrders.json')
const { abi } = JSON.parse(readFileSync(artifact, 'utf8'))

const out = `// Generated by scripts/gen-abi.mjs from contracts/out. Do not edit by hand.
export const canteenOrdersAbi = ${JSON.stringify(abi, null, 2)} as const
`
writeFileSync(resolve(here, '../src/abi.ts'), out)
console.log(`wrote src/abi.ts (${abi.length} entries)`)
